services:
  - type: web
    name: render-truth-watcher
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PROFILE_URL
        value: https://truthsocial.com/@realDonaldTrump
      - key: POLL_MS
        value: "10000"
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
